config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  get "/autoyast", to: "dashboard#autoyast"

  devise_for :users, controllers: { registrations: "auth/registrations",
                                    sessions:      "auth/sessions" }

  resource :dashboard, only: [:index]
  resource :updates, only: [:create]

  get "/assign_nodes", to: "dashboard#unassigned_nodes"
  post "/assign_nodes", to: "dashboard#assign_nodes"

  authenticated :user do
    root "dashboard#index", as: :authenticated_root
  end

  devise_scope :user do
    root to: "auth/sessions#new"
  end

  get "/autoyast", to: "dashboard#autoyast"
  get "/kubectl-config", to: redirect("/kubeconfig") # deprecated
  get "/kubeconfig", to: "oidc#index"
  get "/_health", to: "health#index"
  post "/update", to: "salt#update"

  get "/oidc", to: "oidc#index"
  get "/oidc/done", to: "oidc#done"
  post "/oidc/kubeconfig", to: "oidc#kubeconfig"

  namespace :orchestrations do
    resource :bootstrap, only: :create, controller: :bootstrap
    resource :upgrade, only: :create, controller: :upgrade
    resource :migration, only: :create, controller: :migration
    namespace :migration do
      post :check, action: :check_mirror
      post :reboot, action: :reboot_nodes
      get :status
    end
  end

  namespace :setup do
    get "/", action: :welcome
    match "/", action: :configure, via: [:put, :patch]
    get  "worker-bootstrap"
    post :build_cloud_cluster
    get :discovery
    post :discovery, action: :set_roles
    get :bootstrap
    post :bootstrap, action: :do_bootstrap
  end

  resources :minions, only: :destroy do
    delete :force, action: :force_destroy, on: :member
    post "accept-minion", to: "salt#accept_minion"
    post "remove-minion", to: "salt#remove_minion"
    post "reject-minion", to: "salt#reject_minion"
  end

  namespace :internal_api, path: "internal-api" do
    namespace :v1 do
      resource :pillar, only: :show
    end
  end

  namespace :settings do
    get "/", action: :index
    resources :registries
    post :apply
    resources :registry_mirrors, path: :mirrors
    resources :kubelet_compute_resources_reservations, only: [:index, :create]
    resources :auditing, only: [:index, :create]
    resources :system_certificates
    resources :ldap_test
    resources :dex_connector_ldaps, path: :ldap_connectors
    resources :dex_connector_oidcs, path: :oidc_connectors
    resources :external_cert, only: [:index, :create]
  end
end
# rubocop:enable Metrics/BlockLength

app/controllers/dashboard_controller.rb
require "velum/suse_connect"
require "velum/autoyast_values"

# DashboardController shows the main page.
class DashboardController < ApplicationController
  include Discovery

  # TODO: move autoyast to its own controller (following a different logic flow). It would never get
  # authenticated (as login/password -- since it's machines requesting this endpoint). It would
  # never get redirected to setup the cluster, and it should actually read some security setting for
  # only serving the autoyast profile to a set of IP ranges (provided by the customer).
  skip_before_action :authenticate_user!, only: :autoyast
  skip_before_action :redirect_to_setup, only: :autoyast
  # make sure that access comes from a registered host
  before_action :host_warning, unless: :known_host?

  # The index method is provided through the Discovery concern.
  alias index discovery

  before_action :redirect_to_dashboard, only: :unassigned_nodes

  # Return the autoyast XML profile to bootstrap other worker nodes. They will read this response in
  # order to start an unattended installation of CaaSP.
  #
  # It will return the content of the autoyast profile along with a 200 HTTP response code if the
  # operation was successfull, or a 503 HTTP response code (service unavailable) if there was any
  # problem while contacting to the subscription backend.
  #
  # This method skips authentication (workers won't authenticate using the typical username/password
  # fields that customer uses) and also skips the redirection to the setup process (when a worker
  # asks for the autoyast profile we will either serve it, or return an error).
  def autoyast
    pollute_variables!(Velum::AutoyastValues.new)
    if @controller_node.blank?
      head :service_unavailable
    else
      render "autoyast.xml.erb", layout: false, content_type: "text/xml"
    end
  end

  # GET /assign_nodes
  def unassigned_nodes
    @unassigned_minions = Minion.unassigned_role
    @assigned_minions_hostnames = Minion.cluster_role.pluck(:fqdn)
  end

  # POST /assign_nodes
  def assign_nodes
    assigned = Minion.assign_roles roles: update_nodes_params, remote: true
    if assigned.values.include?(false)
      redirect_to assign_nodes_path,
                  flash: { error: "Failed to assign #{failed_assigned_nodes(assigned)}" }
    else
      Orchestration.run
      redirect_to authenticated_root_path
    end
  end

  private

  def update_nodes_params
    params.require(:roles).permit(worker: [], master: [])
  end

  def redirect_to_dashboard
    redirect_to root_path unless setup_done?
  end

  def failed_assigned_nodes(assigned)
    assigned.reject { |_name, success| success }.keys.join(", ")
  end

  def host_warning
    flash[:alert] = "You are accessing velum from an unregistered host (#{request.host}). " \
                    "It is advised to access velum via one of the registered hosts " \
                    "#{accessible_hosts.join(" or ")}"
  end

  # This method will copy *all* instance variables of the given object to the
  # current instance. No checks will be performed if a variable already exists -
  # the current value will be overwritten in that case.
  #
  # This copying right now is used to prevent nesting values in the template:
  # instead of writing `<%= other.var %>` it is possible to just write `<%= var
  # %>` again.
  #
  # @param other [Object] Any object with instance variables.
  def pollute_variables!(other)
    other.instance_variables.each do |var|
      instance_variable_set(var, other.instance_variable_get(var))
    end
  end
end

app/views/dashboard/_pending_nodes.html.slim
.pending-nodes-container data-url=authenticated_root_path
  .panel.panel-default
    .panel-heading
      h3.panel-title Pending Nodes

      button#accept-all.btn.btn-sm.btn-default.pull-right disabled="disabled"
        i.fa.fa-check.fa-fw
        | Accept All Nodes

    .panel-body
      .row.nodes-loading
        p.text-center
          i class="fa fa-spinner fa-pulse fa-3x fa-fw"
          span class="sr-only" Loading...
      .nodes-content.hidden
        p.empty-text
          | You currently have no nodes to be accepted for bootstrapping.
        .has-content.hidden
          p Accepting nodes into the cluster might take a while. Be aware that it's not possible to accept a new node while another node is being bootstrapped.

          table.table
            thead
              tr
                th
                  | ID
                th width="30%"
                  | Actions
            tbody

app/views/dashboard/_polling.html.slim
= content_for :page_javascript do
  javascript:
    MinionPoller.renderMode = "Dashboard";
    MinionPoller.poll();

app/views/dashboard/_warn_node_removal_modal.html.slim
.modal.fade.warn-node-removal-modal aria-labelledby="modal-label" role="dialog" tabindex="-1"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"
            | &times;
        h4#modal-label.modal-title
          | Unsupported cluster topology
      .modal-body
        p By removing the respective node you'll be breaking the following constraints that is needed to have a stable and supported topology:
        ul.node-removal-constraints-list
      .modal-footer
        button.btn.btn-default data-dismiss="modal" type="button"
          | Cancel
        button.btn.btn-primary.remove-anyway type="button"
          | Proceed anyway

app/views/dashboard/autoyast.xml.erb
<?xml version="1.0"?>
<!DOCTYPE profile>
<profile xmlns="http://www.suse.com/1.0/yast2ns" xmlns:config="http://www.suse.com/1.0/configns">
  <scripts>
    <chroot-scripts config:type="list">
      <script>
        <chrooted config:type="boolean">true</chrooted>
        <filename>set_salt_master.sh</filename>
        <interpreter>shell</interpreter>
        <source><![CDATA[
        #!/bin/sh
        echo "master: <%= @controller_node %>" > /etc/salt/minion.d/minion.conf
        echo "grains_refresh_every: 10" > /etc/salt/minion.d/grains_refresh.conf
        ]]>
        </source>
      </script>
      <script>
        <chrooted config:type="boolean">true</chrooted>
        <filename>configure_timesyncd.sh</filename>
        <interpreter>shell</interpreter>
        <source><![CDATA[
        #!/bin/sh
        sed -i -e 's|#NTP=.*|NTP=<%= @controller_node %>|g' /etc/systemd/timesyncd.conf
        timedatectl set-ntp true
        ]]>
        </source>
      </script>
<% unless @ssh_public_key.blank? %>
      <script>
        <chrooted config:type="boolean">true</chrooted>
        <filename>set_authorized_keys.sh</filename>
        <interpreter>shell</interpreter>
        <source><![CDATA[
        #!/bin/sh
        mkdir -p /root/.ssh
        chmod 600 /root/.ssh
        echo "<%= @ssh_public_key %>" > /root/.ssh/authorized_keys
        ]]>
        </source>
      </script>
<% end %>
<% if @proxy_systemwide %>
      <script>
        <chrooted config:type="boolean">true</chrooted>
        <filename>set_proxy.sh</filename>
        <interpreter>shell</interpreter>
        <source><![CDATA[
        #!/bin/sh
        sed -i -e 's|PROXY_ENABLED=".*"|PROXY_ENABLED="yes"|g' /etc/sysconfig/proxy
<% unless @proxy_http.blank? %>
        sed -i -e 's|HTTP_PROXY=".*"|HTTP_PROXY="<%= @proxy_http %>"|g' /etc/sysconfig/proxy
        echo '--proxy "<%= @proxy_http %>"' >> /root/.curlrc
<% end %>
<% unless @proxy_https.blank? %>
        sed -i -e 's|HTTPS_PROXY=".*"|HTTPS_PROXY="<%= @proxy_https %>"|g' /etc/sysconfig/proxy
<% end %>
<% unless @proxy_no_proxy.blank? %>
        sed -i -e 's|NO_PROXY=".*"|NO_PROXY="<%= @proxy_no_proxy %>"|g' /etc/sysconfig/proxy
        echo '--noproxy "<%= @proxy_no_proxy %>"' >> /root/.curlrc
<% end %>
        ]]>
        </source>
      </script>
<% end %>
    </chroot-scripts>
  </scripts>
  <bootloader>
    <global>
      <generic_mbr>true</generic_mbr>
      <gfxmode>auto</gfxmode>
      <hiddenmenu>false</hiddenmenu>
      <os_prober>false</os_prober>
      <terminal>gfxterm</terminal>
      <timeout config:type="integer">8</timeout>
      <suse_btrfs config:type="boolean">true</suse_btrfs>
    </global>
  </bootloader>
  <general>
    <ask-list config:type="list"/>
    <mode>
      <confirm config:type="boolean">false</confirm>
      <second_stage config:type="boolean">false</second_stage>
      <self_update config:type="boolean">false</self_update>
    </mode>
    <proposals config:type="list"/>
    <storage>
      <partition_alignment config:type="symbol">align_optimal</partition_alignment>
      <start_multipath config:type="boolean">false</start_multipath>
    </storage>
  </general>
  <partitioning config:type="list">
    <drive>
      <use>all</use>
      <partitions config:type="list">
        <partition>
          <mount>/boot/efi</mount>
          <size>200mb</size>
          <partition_id config:type="integer">1</partition_id>
          <filesystem config:type="symbol">vfat</filesystem>
        </partition>
        <partition>
          <mount>/</mount>
          <size>30gb</size>
        </partition>
        <partition>
          <filesystem config:type="symbol">btrfs</filesystem>
          <mount>/var/lib/docker</mount>
          <size>max</size>
        </partition>
      </partitions>
    </drive>
  </partitioning>
  <ssh_import>
    <copy_config config:type="boolean">false</copy_config>
    <import config:type="boolean">false</import>
  </ssh_import>
  <keyboard>
    <keymap><%= @keyboard_layout %></keymap>
  </keyboard>
  <language>
    <language>en_US</language>
    <languages/>
  </language>
  <timezone>
    <hwclock>UTC</hwclock>
    <timezone>Etc/GMT</timezone>
  </timezone>
  <networking>
    <dhcp_options>
      <dhclient_client_id/>
      <dhclient_hostname_option>AUTO</dhclient_hostname_option>
    </dhcp_options>
    <dns>
      <dhcp_hostname config:type="boolean">true</dhcp_hostname>
      <resolv_conf_policy>auto</resolv_conf_policy>
      <write_hostname config:type="boolean">false</write_hostname>
    </dns>
    <interfaces config:type="list">
      <interface>
        <bootproto>dhcp</bootproto>
        <device>eth0</device>
        <dhclient_set_default_route>yes</dhclient_set_default_route>
        <startmode>auto</startmode>
      </interface>
      <interface>
        <bootproto>static</bootproto>
        <device>lo</device>
        <firewall>no</firewall>
        <ipaddr>127.0.0.1</ipaddr>
        <netmask>255.0.0.0</netmask>
        <network>127.0.0.0</network>
        <prefixlen>8</prefixlen>
        <startmode>nfsroot</startmode>
        <usercontrol>no</usercontrol>
      </interface>
    </interfaces>
    <ipv6 config:type="boolean">true</ipv6>
    <keep_install_network config:type="boolean">true</keep_install_network>
    <setup_before_proposal config:type="boolean">true</setup_before_proposal>
    <managed config:type="boolean">false</managed>
    <routing>
      <ipv4_forward config:type="boolean">false</ipv4_forward>
      <ipv6_forward config:type="boolean">false</ipv6_forward>
    </routing>
  </networking>
  <software>
    <image/>
    <install_recommended config:type="boolean">false</install_recommended>
    <instsource/>
    <patterns config:type="list">
      <pattern>SUSE-MicroOS</pattern>
    </patterns>
    <patterns config:type="list">
      <pattern>SUSE-CaaSP-Stack</pattern>
    </patterns>
  </software>
  <services-manager>
    <default_target>multi-user</default_target>
    <services>
      <disable config:type="list">
        <service>purge-kernels</service>
      </disable>
      <enable config:type="list">
        <service>sshd</service>
        <service>cloud-init-local</service>
        <service>cloud-init</service>
        <service>cloud-config</service>
        <service>cloud-final</service>
        <service>issue-generator</service>
        <service>issue-add-ssh-keys</service>
        <service>salt-minion</service>
        <service>systemd-timesyncd</service>
        <service>docker</service>
        <service>container-feeder</service>
      </enable>
    </services>
  </services-manager>
  <users config:type="list">
    <user>
      <username>root</username>
      <user_password>!</user_password>
      <encrypted config:type="boolean">true</encrypted>
    </user>
  </users>
  <suse_register>
    <do_registration config:type="boolean"><%= @do_registration %></do_registration>
    <% unless @suse_regcode.blank? %>
      <reg_code><%= @suse_regcode %></reg_code>
    <% end %>
    <install_updates config:type="boolean">true</install_updates>
    <slp_discovery config:type="boolean">false</slp_discovery>
    <% unless @suse_smt_url.blank? %>
      <reg_server><%= @suse_smt_url %></reg_server>
    <% end %>
  </suse_register>
</profile>

app/views/dashboard/index.html.slim
.alert.alert-warning.unsupported-alert role="alert" hidden="true"
  i.fa.fa-4x.pull-left aria-hidden="true"
  span
    | A supported deployment of #{product_name} requires&nbsp;
    span class="reason"
    | .

.alert.alert-danger.repomirror-sync-alert role="alert" hidden="true"
  i.fa.fa-4x.pull-left aria-hidden="true"
  span
    | Your local RMT/SMT mirror looks like it's out of sync. Click #{link_to "here", orchestrations_migration_check_path, method: :post} to perform another check.

h1 Cluster Status

.nodes-summary
  .panel.panel-default
    .panel-heading
      h3.panel-title Summary
    .panel-body
      .row.summary-loading
        p.text-center
          i class="fa fa-spinner fa-pulse fa-3x fa-fw"
          span class="sr-only" Loading...
      .row.summary-content.hidden
        .col-md-6.left-column
          dl.side-by-side
            dt Total nodes
            dd.assigned-count
            dt Master nodes
            dd.master-count
            dt Unassigned nodes
            dd.unassigned-count data-url=assign_nodes_url
        .col-md-6.right-column
          dl.side-by-side
            dt Updates
            dd Manual
            dt # of nodes w/ outdated software
            dd.outdated-count
              span#out_dated_nodes 0
              = link_to update_path, id: "update-all-nodes", class: "hidden", method: :post do
                | (update all nodes)
              = link_to orchestrations_migration_reboot_path, id: "migrate-all-nodes", class: "hidden", method: :post do
                | (migrate all nodes)
    .panel-footer.admin-outdated-notification.hidden
      .message
        i.fa.fw.fa-exclamation-circle
        strong Admin node is running outdated software
      .failed-message
        i.fa.fw.fa-exclamation-circle
        strong An error occurred during the admin node update process
      .actions
        a.btn.btn-link.update-admin-btn data-toggle="modal" data-target=".update-admin-modal"
          | Update admin node
    .panel-footer.admin-migration-notification.hidden
      .message
        i.fa.fw.fa-exclamation-circle
        strong Cluster has migration available
      .failed-message
        i.fa.fw.fa-exclamation-circle
        strong An error occurred during the admin node migration process
      .actions
        a.btn.btn-link.migrate-admin-btn data-toggle="modal" data-target=".migrate-admin-modal"
          | Migrate admin node

.nodes-container data-url=authenticated_root_path
  .panel.panel-default
    .panel-heading
      h3.panel-title Nodes

      = link_to kubeconfig_path, id: "download-kubeconfig", class: "btn btn-sm btn-default pull-right", disabled: true do
        i.fa.fa-download.fa-fw
        | kubeconfig

      = link_to orchestrations_bootstrap_path, method: :post, id: "retry-cluster-bootstrap", class: "hidden btn btn-sm btn-primary pull-right" do
        i.fa.fa-refresh.fa-fw
        | Retry cluster bootstrap

      = link_to orchestrations_upgrade_path, method: :post, id: "retry-cluster-upgrade", class: "hidden btn btn-sm btn-primary pull-right" do
        i.fa.fa-refresh.fa-fw
        | Retry cluster update

      = link_to orchestrations_migration_reboot_path, method: :post, id: "retry-cluster-migration", class: "hidden btn btn-sm btn-primary pull-right" do
        i.fa.fa-refresh.fa-fw
        | Retry cluster migration

      = link_to setup_worker_bootstrap_path, id: "add-nodes", class: "btn btn-sm btn-success pull-right" do
        i.fa.fa-plus.fa-fw
        | Add node

    .panel-body
      .row.nodes-loading
        p.text-center
          i class="fa fa-spinner fa-pulse fa-3x fa-fw"
          span class="sr-only" Loading...
      .nodes-content.hidden
        table.table
          thead
            tr
              th
                | Online
              th
                | Applied
              th
                | ID
              th
                | Hostname
              th
                | Role
              th width="130"
                | Actions
          tbody

= render "dashboard/pending_nodes"
= render "dashboard/modals/update_admin_modal"
= render "dashboard/modals/migrate_admin_modal"
= render "dashboard/modals/warn_mirror_sync_modal"
= render "dashboard/modals/warn_node_removal_modal"
= render "dashboard/modals/warn_node_force_removal_modal"
= render "dashboard/polling"

app/views/dashboard/unassigned_nodes.html.slim
.alert.alert-info.alert-dismissible role="alert"
  button.close[type="button" data-dismiss="alert" aria-label="Close"]
    span[aria-hidden="true"]
      | &times;
  i.fa.fa-4x.pull-left aria-hidden="true"
  span
    | After selecting the respective nodes' by choosing their roles and clicking on "Add nodes", all of them will be assigned and added to the cluster.

.alert.alert-danger.unassigned-alert role="alert" hidden="true"
  i.fa.fa-4x.pull-left aria-hidden="true"
  span
    p Unable to add nodes:

    ul.list

h1 Unassigned Nodes

.panel.panel-default.unassigned-nodes-panel class=('hide' unless any_minion?)
  .panel-heading
    h3.panel-title#node-count #{@unassigned_minions.count} nodes found

    button.btn.btn-sm.btn-default.pull-right.select-nodes-btn title="Select remaining nodes as worker"
      i.fa.fa-check.fa-fw
      | Select remaining nodes

    button.btn.btn-sm.btn-default.pull-right.hidden.deselect-nodes-btn title="Deselect all the nodes"
      i.fa.fa-times.fa-fw
      | Deselect all nodes

  .panel-body
    = form_tag(assign_nodes_url, method: "post")
      div class="nodes-container new-nodes-container" data-url=authenticated_root_path data-current-hostnames='#{@assigned_minions_hostnames}'
        table.table
          thead
            tr
              th
                | ID
              th
                | Hostname
              th width="235"
                | Role
              th width="90"
                | Actions
          tbody
            tr
              td colspan=4
                p.text-center
                  i class="fa fa-spinner fa-pulse fa-3x fa-fw"
                  span class="sr-only" Loading...

        hr

        .clearfix.text-right.steps-container
          = link_to "Back", authenticated_root_path, class: "btn btn-default"
          | &nbsp;
          = submit_tag "Add nodes", class: "btn btn-primary add-nodes-btn", disabled: true

= content_for :page_javascript do
  javascript:
    MinionPoller.renderMode = "Unassigned";
    MinionPoller.poll();