config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  get "/autoyast", to: "dashboard#autoyast"

  devise_for :users, controllers: { registrations: "auth/registrations",
                                    sessions:      "auth/sessions" }

  resource :dashboard, only: [:index]
  resource :updates, only: [:create]

  get "/assign_nodes", to: "dashboard#unassigned_nodes"
  post "/assign_nodes", to: "dashboard#assign_nodes"

  authenticated :user do
    root "dashboard#index", as: :authenticated_root
  end

  devise_scope :user do
    root to: "auth/sessions#new"
  end

  get "/autoyast", to: "dashboard#autoyast"
  get "/kubectl-config", to: redirect("/kubeconfig") # deprecated
  get "/kubeconfig", to: "oidc#index"
  get "/_health", to: "health#index"
  post "/update", to: "salt#update"

  get "/oidc", to: "oidc#index"
  get "/oidc/done", to: "oidc#done"
  post "/oidc/kubeconfig", to: "oidc#kubeconfig"

  namespace :orchestrations do
    resource :bootstrap, only: :create, controller: :bootstrap
    resource :upgrade, only: :create, controller: :upgrade
    resource :migration, only: :create, controller: :migration
    namespace :migration do
      post :check, action: :check_mirror
      post :reboot, action: :reboot_nodes
      get :status
    end
  end

  namespace :setup do
    get "/", action: :welcome
    match "/", action: :configure, via: [:put, :patch]
    get  "worker-bootstrap"
    post :build_cloud_cluster
    get :discovery
    post :discovery, action: :set_roles
    get :bootstrap
    post :bootstrap, action: :do_bootstrap
  end

  resources :minions, only: :destroy do
    delete :force, action: :force_destroy, on: :member
    post "accept-minion", to: "salt#accept_minion"
    post "remove-minion", to: "salt#remove_minion"
    post "reject-minion", to: "salt#reject_minion"
  end

  namespace :internal_api, path: "internal-api" do
    namespace :v1 do
      resource :pillar, only: :show
    end
  end

  namespace :settings do
    get "/", action: :index
    resources :registries
    post :apply
    resources :registry_mirrors, path: :mirrors
    resources :kubelet_compute_resources_reservations, only: [:index, :create]
    resources :auditing, only: [:index, :create]
    resources :system_certificates
    resources :ldap_test
    resources :dex_connector_ldaps, path: :ldap_connectors
    resources :dex_connector_oidcs, path: :oidc_connectors
    resources :external_cert, only: [:index, :create]
  end
end
# rubocop:enable Metrics/BlockLength

app/views/shared/_header.html.slim
header.main-header
  .navbar-header
    button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
      span class="sr-only"
        | Toggle navigation
      span class="icon-bar"
      span class="icon-bar"
      span class="icon-bar"
    = link_to root_path, class: "navbar-brand" do
      = image_tag("branding/logo.svg", class: "logo")

  #navbar class="navbar-collapse collapse"
    - if setup_done?
      ul class="nav navbar-nav navbar-nav-menu"
          li class="#{active_class?(root_path)}"
            = link_to("Home", root_path, class: "")
          li class="#{active_class?(settings_path?)}"
            = link_to("Settings", settings_path, class: "")

    ul class="nav navbar-nav navbar-right"
      li
        = link_to('Logout', destroy_user_session_path, class: "btn btn-logout", :method => :delete)

app/views/shared/_notification.html.slim
.alert.alert-dismissible.fade.in.text-left[class="#{klass} alert-#{alert == 'alert' ? 'danger' : 'info'}"]
  button.close class="alert-hide" type="button" data-dismiss="alert"
    span aria-hidden="true" &times;
    span.sr-only Close
  .alert-message
    .alert-icon.pull-left
      i.fa.fa-3x.pull-left class=(alert == 'alert' ? 'fa-exclamation-circle' : 'fa-info-circle')
    span
      - if messages.is_a?(String)
        = messages
      - elsif messages.is_a?(Array)
        - if messages.size == 1
          = messages[0]
        - else
          ul
            - messages.each do |c|
              li
                = c

app/views/shared/_notifications.html.slim
- flash.each do |key, value|
  - if key == 'notice' || key == 'alert'
    = render template: 'shared/_notification.html.slim',
        locals: { messages: value, alert: key, klass: "" }

= render template: 'shared/_notification.html.slim',
    locals: { messages: "Could not connect with Velum API. If you're bootstrapping for the first time, this is expected due to an update of our certificate. Please, try #{link_to "reloading the session", root_path}.".html_safe, alert: "alert", klass: "connection-failed-alert" }