config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  get "/autoyast", to: "dashboard#autoyast"

  devise_for :users, controllers: { registrations: "auth/registrations",
                                    sessions:      "auth/sessions" }

  resource :dashboard, only: [:index]
  resource :updates, only: [:create]

  get "/assign_nodes", to: "dashboard#unassigned_nodes"
  post "/assign_nodes", to: "dashboard#assign_nodes"

  authenticated :user do
    root "dashboard#index", as: :authenticated_root
  end

  devise_scope :user do
    root to: "auth/sessions#new"
  end

  get "/autoyast", to: "dashboard#autoyast"
  get "/kubectl-config", to: redirect("/kubeconfig") # deprecated
  get "/kubeconfig", to: "oidc#index"
  get "/_health", to: "health#index"
  post "/update", to: "salt#update"

  get "/oidc", to: "oidc#index"
  get "/oidc/done", to: "oidc#done"
  post "/oidc/kubeconfig", to: "oidc#kubeconfig"

  namespace :orchestrations do
    resource :bootstrap, only: :create, controller: :bootstrap
    resource :upgrade, only: :create, controller: :upgrade
    resource :migration, only: :create, controller: :migration
    namespace :migration do
      post :check, action: :check_mirror
      post :reboot, action: :reboot_nodes
      get :status
    end
  end

  namespace :setup do
    get "/", action: :welcome
    match "/", action: :configure, via: [:put, :patch]
    get  "worker-bootstrap"
    post :build_cloud_cluster
    get :discovery
    post :discovery, action: :set_roles
    get :bootstrap
    post :bootstrap, action: :do_bootstrap
  end

  resources :minions, only: :destroy do
    delete :force, action: :force_destroy, on: :member
    post "accept-minion", to: "salt#accept_minion"
    post "remove-minion", to: "salt#remove_minion"
    post "reject-minion", to: "salt#reject_minion"
  end

  namespace :internal_api, path: "internal-api" do
    namespace :v1 do
      resource :pillar, only: :show
    end
  end

  namespace :settings do
    get "/", action: :index
    resources :registries
    post :apply
    resources :registry_mirrors, path: :mirrors
    resources :kubelet_compute_resources_reservations, only: [:index, :create]
    resources :auditing, only: [:index, :create]
    resources :system_certificates
    resources :ldap_test
    resources :dex_connector_ldaps, path: :ldap_connectors
    resources :dex_connector_oidcs, path: :oidc_connectors
    resources :external_cert, only: [:index, :create]
  end
end
# rubocop:enable Metrics/BlockLength

app/controllers/dashboard_controller.rb
require "velum/suse_connect"
require "velum/autoyast_values"

# DashboardController shows the main page.
class DashboardController < ApplicationController
  include Discovery

  # TODO: move autoyast to its own controller (following a different logic flow). It would never get
  # authenticated (as login/password -- since it's machines requesting this endpoint). It would
  # never get redirected to setup the cluster, and it should actually read some security setting for
  # only serving the autoyast profile to a set of IP ranges (provided by the customer).
  skip_before_action :authenticate_user!, only: :autoyast
  skip_before_action :redirect_to_setup, only: :autoyast
  # make sure that access comes from a registered host
  before_action :host_warning, unless: :known_host?

  # The index method is provided through the Discovery concern.
  alias index discovery

  before_action :redirect_to_dashboard, only: :unassigned_nodes

  # Return the autoyast XML profile to bootstrap other worker nodes. They will read this response in
  # order to start an unattended installation of CaaSP.
  #
  # It will return the content of the autoyast profile along with a 200 HTTP response code if the
  # operation was successfull, or a 503 HTTP response code (service unavailable) if there was any
  # problem while contacting to the subscription backend.
  #
  # This method skips authentication (workers won't authenticate using the typical username/password
  # fields that customer uses) and also skips the redirection to the setup process (when a worker
  # asks for the autoyast profile we will either serve it, or return an error).
  def autoyast
    pollute_variables!(Velum::AutoyastValues.new)
    if @controller_node.blank?
      head :service_unavailable
    else
      render "autoyast.xml.erb", layout: false, content_type: "text/xml"
    end
  end

  # GET /assign_nodes
  def unassigned_nodes
    @unassigned_minions = Minion.unassigned_role
    @assigned_minions_hostnames = Minion.cluster_role.pluck(:fqdn)
  end

  # POST /assign_nodes
  def assign_nodes
    assigned = Minion.assign_roles roles: update_nodes_params, remote: true
    if assigned.values.include?(false)
      redirect_to assign_nodes_path,
                  flash: { error: "Failed to assign #{failed_assigned_nodes(assigned)}" }
    else
      Orchestration.run
      redirect_to authenticated_root_path
    end
  end

  private

  def update_nodes_params
    params.require(:roles).permit(worker: [], master: [])
  end

  def redirect_to_dashboard
    redirect_to root_path unless setup_done?
  end

  def failed_assigned_nodes(assigned)
    assigned.reject { |_name, success| success }.keys.join(", ")
  end

  def host_warning
    flash[:alert] = "You are accessing velum from an unregistered host (#{request.host}). " \
                    "It is advised to access velum via one of the registered hosts " \
                    "#{accessible_hosts.join(" or ")}"
  end

  # This method will copy *all* instance variables of the given object to the
  # current instance. No checks will be performed if a variable already exists -
  # the current value will be overwritten in that case.
  #
  # This copying right now is used to prevent nesting values in the template:
  # instead of writing `<%= other.var %>` it is possible to just write `<%= var
  # %>` again.
  #
  # @param other [Object] Any object with instance variables.
  def pollute_variables!(other)
    other.instance_variables.each do |var|
      instance_variable_set(var, other.instance_variable_get(var))
    end
  end
end

app/views/dashboard/modals/_migrate_admin_modal.html.erb
<div class="modal fade migrate-admin-modal" tabindex="-1" role="dialog" aria-labelledby="modal-label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="modal-label">
          A new version of SUSE CaaS Platform is available
        </h4>
      </div>
      <div class="modal-body">
  <% if Minion.admin.first.tx_update_migration_notes =~ /^http.*/ %>
        <p>You can find the release notes <a target="_blank" href="<%= Minion.admin.first.tx_update_migration_notes %>">here.</a></p>
  <% end %>
        <p>The migration will take some time, as there could be larger updates which need to be downloaded first.</p>
        <p>Once the migration is installed, the admin node gets rebooted.</p>
        <p>After this you can proceed with the migration with the rest of your cluster nodes</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary trigger-migrate-admin-btn" data-url="<%= orchestrations_migration_url %>" data-migration-check="<%= orchestrations_migration_status_url %>">
          Migrate admin
        </button>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/modals/_update_admin_modal.html.erb
<div class="modal fade update-admin-modal" tabindex="-1" role="dialog" aria-labelledby="modal-label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="modal-label">
          The admin node needs to reboot in order to apply the software update
        </h4>
      </div>
      <div class="modal-body">
       <p>Rebooting the admin node will break ongoing operations like the creation of the cluster, the addition or removal of nodes and upgrades.</p>
       <p>Please ensure none of the following operations are ongoing before proceeding with the upgrade of the admin node.</p>
       <p>Once the admin node is rebooted, the page will be refreshed.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary reboot-update-btn" data-url="<%= updates_url %>" data-health-check="<%= _health_url %>">
          Reboot to update
        </button>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/modals/_warn_mirror_sync_modal.html.erb
<div class="modal fade warn-mirror-sync-modal" tabindex="-1" role="dialog" aria-labelledby="modal-label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="modal-label">
          Your mirrors seem to be out of sync
        </h4>
      </div>
      <div class="modal-body">
        <p>Cannot run migration with out of date mirrors.</p>
        <p>Please synchronize your local RMT/SMT Mirror(s) first.</p>
        <br>
        <p>Click 'Confirm' when your mirror is synced. This will perform a sanity check.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary confirm-mirror-synced-btn" data-url="<%= orchestrations_migration_check_url %>">
          Confirm
        </button>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/modals/_warn_node_force_removal_modal.html.slim
.modal.fade.warn-node-force-removal-modal aria-labelledby="modal-label" role="dialog" tabindex="-1"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"
            | &times;
        h4#modal-label.modal-title
          | Forced node removal
      .modal-body
        p You are about to forcibly remove a node from the cluster. This action cannot be reversed.
          Any data on this node will be lost and the machine must be re-installed before it can be
          added back.

        p The operation will perform some basic tasks to maintain the coherence of the cluster, but
          it may not function normally afterwards.

        p Only proceed with this operation if you are certain it is essential to do so.
      .modal-footer
        button.btn.btn-default data-dismiss="modal" type="button"
          | Cancel
        button.btn.btn-primary.force-remove-anyway type="button"
          | Proceed with forcible removal

app/views/dashboard/modals/_warn_node_removal_modal.html.slim
.modal.fade.warn-node-removal-modal aria-labelledby="modal-label" role="dialog" tabindex="-1"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"
            | &times;
        h4#modal-label.modal-title
          | Unsupported cluster topology
      .modal-body
        p By removing the respective node you'll be breaking the following constraints that is needed to have a stable and supported topology:
        ul.constraints-list
      .modal-footer
        button.btn.btn-default data-dismiss="modal" type="button"
          | Cancel
        button.btn.btn-primary.remove-anyway type="button"
          | Proceed anyway