config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  get "/autoyast", to: "dashboard#autoyast"

  devise_for :users, controllers: { registrations: "auth/registrations",
                                    sessions:      "auth/sessions" }

  resource :dashboard, only: [:index]
  resource :updates, only: [:create]

  get "/assign_nodes", to: "dashboard#unassigned_nodes"
  post "/assign_nodes", to: "dashboard#assign_nodes"

  authenticated :user do
    root "dashboard#index", as: :authenticated_root
  end

  devise_scope :user do
    root to: "auth/sessions#new"
  end

  get "/autoyast", to: "dashboard#autoyast"
  get "/kubectl-config", to: redirect("/kubeconfig") # deprecated
  get "/kubeconfig", to: "oidc#index"
  get "/_health", to: "health#index"
  post "/update", to: "salt#update"

  get "/oidc", to: "oidc#index"
  get "/oidc/done", to: "oidc#done"
  post "/oidc/kubeconfig", to: "oidc#kubeconfig"

  namespace :orchestrations do
    resource :bootstrap, only: :create, controller: :bootstrap
    resource :upgrade, only: :create, controller: :upgrade
    resource :migration, only: :create, controller: :migration
    namespace :migration do
      post :check, action: :check_mirror
      post :reboot, action: :reboot_nodes
      get :status
    end
  end

  namespace :setup do
    get "/", action: :welcome
    match "/", action: :configure, via: [:put, :patch]
    get  "worker-bootstrap"
    post :build_cloud_cluster
    get :discovery
    post :discovery, action: :set_roles
    get :bootstrap
    post :bootstrap, action: :do_bootstrap
  end

  resources :minions, only: :destroy do
    delete :force, action: :force_destroy, on: :member
    post "accept-minion", to: "salt#accept_minion"
    post "remove-minion", to: "salt#remove_minion"
    post "reject-minion", to: "salt#reject_minion"
  end

  namespace :internal_api, path: "internal-api" do
    namespace :v1 do
      resource :pillar, only: :show
    end
  end

  namespace :settings do
    get "/", action: :index
    resources :registries
    post :apply
    resources :registry_mirrors, path: :mirrors
    resources :kubelet_compute_resources_reservations, only: [:index, :create]
    resources :auditing, only: [:index, :create]
    resources :system_certificates
    resources :ldap_test
    resources :dex_connector_ldaps, path: :ldap_connectors
    resources :dex_connector_oidcs, path: :oidc_connectors
    resources :external_cert, only: [:index, :create]
  end
end
# rubocop:enable Metrics/BlockLength

app/controllers/settings/admission_webhook_controller.rb
# Settings::AdmissionWebhook is responsibe to manage all the requests
# related to the kubernetes auditing feature.
class Settings::AdmissionWebhookController < SettingsController
  def index
    @form = AdmissionWebhookForm.new
    set_instance_variables
  end

  def create
    @form = AdmissionWebhookForm.new(admission_webhook_params)

    if @form.valid?
      @errors = Pillar.apply(
        admission_webhook_pillars,
        unprotected_pillars: admission_webhook_pillars.keys
      )
    end

    if @form.valid? && @errors.empty?
      redirect_to settings_admission_webhook_index_path,
        notice: "Admission webhook settings successfully saved."
    else
      set_instance_variables
      render action: :index, status: :unprocessable_entity
    end
  end

  private

  def set_instance_variables
    @admission_webhook_enabled = @form.enabled == "true" ||
      Pillar.value(pillar: :api_admission_webhook_enabled) == "true"
    @certificate = Pillar.value(pillar: :api_admission_webhook_cert)
    @key = Pillar.value(pillar: :api_admission_webhook_key)
    @errors ||= []
  end

  def admission_webhook_params
    params.require(
      :admission_webhook
    ).permit(
      :enabled,
      :cert_file,
      :key_file,
      :current_cert,
      :current_key
    )
  end

  def admission_webhook_pillars
    ret = {
      api_admission_webhook_enabled: @form.enabled,
      api_admission_webhook_cert:    nil,
      api_admission_webhook_key:     nil
    }

    return ret if @form.enabled == "false"

    ret[:api_admission_webhook_cert] = @form.certificate || @form.current_cert
    ret[:api_admission_webhook_key] = @form.key || @form.current_key

    ret
  end
end

app/controllers/settings/auditing_controller.rb
# Settings::Auditing is responsibe to manage all the requests
# related to the kubernetes auditing feature.
class Settings::AuditingController < SettingsController
  def index
    set_instance_variables
  end

  def create
    @errors = Pillar.apply audit_params
    if @errors.empty?
      redirect_to settings_auditing_index_path,
        notice: "Auditing settings successfully saved."
    else
      set_instance_variables
      render action: :index, status: :unprocessable_entity
    end
  end

  private

  def set_instance_variables
    @audit_enabled = Pillar.value(pillar: :api_audit_log_enabled) || "false"
    @maxsize = Pillar.value(pillar: :api_audit_log_maxsize) || 10
    @maxage = Pillar.value(pillar: :api_audit_log_maxage) || 15
    @maxbackup = Pillar.value(pillar: :api_audit_log_maxbackup) || 20
    @policy = Pillar.value(pillar: :api_audit_log_policy) || ""
  end

  def audit_params
    ret = {}
    params.require(
      :audit
    ).permit(
      :enabled,
      :maxage,
      :maxsize,
      :maxbackup,
      :policy
    ).each do |k, v|
      ret["api_audit_log_#{k}".to_sym] = v
    end
    ret
  end
end

app/controllers/settings/base_certificate_controller.rb
# Settings::BaseCertificateController extract common methods for certificate
# handling in controllers.
#
# It expects the instance to be assigned to @certificate_holder and will
# set this variable before the `update` & `delete` routes.
#
# Subclasses are expected to overwrite the following methods:
#
# - @certificate_holder: the instance that holds the reference to the
#                        certificate
#
# - certificate_holder_type: return the class that will hold a reference to a
#                       certificate
#
# - certificate_holder_params: parameters that can be used to create a new
#                              certificate_holder model
#
# - certificate_holder_update_params: parameters that can be used to update the
#                                     certificate_holder model
class Settings::BaseCertificateController < SettingsController
  before_action :set_certificate_holder, except: [:index, :new, :create]

  attr_accessor :certificate_holder

  def new
    @certificate_holder = certificate_holder_type.new
    @cert = Certificate.new
    @passed_cert = nil
  end

  def create
    @certificate_holder = certificate_holder_type.new(
      certificate_holder_params.except(:certificate, :current_cert)
    )
    @cert = passed_certificate

    ActiveRecord::Base.transaction do
      @certificate_holder.save!
      create_or_update_certificate! if passed_certificate.present?
    end

    redirect_to [:settings, @certificate_holder],
                notice: "#{@certificate_holder.class} was successfully created."
  rescue ActiveRecord::RecordInvalid
    render action: :new, status: :unprocessable_entity
  end

  def edit
    @cert = @certificate_holder.certificate || Certificate.new
  end

  def update
    @cert = @certificate_holder.certificate || passed_certificate

    ActiveRecord::Base.transaction do
      @certificate_holder.update_attributes!(certificate_holder_update_params)

      if passed_certificate.present?
        create_or_update_certificate!
      elsif @certificate_holder.certificate.present?
        @certificate_holder.certificate.destroy!
      end
    end

    redirect_to [:settings, @certificate_holder],
                notice: "#{@certificate_holder.class} was successfully updated."
  rescue ActiveRecord::RecordInvalid
    render action: :edit, status: :unprocessable_entity
  end

  protected

  # Class of ActiveRecord model that will hold the certificate
  #
  # @return [Class] Class of the object that will hold the certificate
  def certificate_holder_type
    raise NotImplementedError,
          "#{self.class.name}#certificate_holder_type is an abstract method."
  end

  # Form parameters that can be used to create instantiate the
  # certificate_holder_type
  #
  # @return [ActiveController::StrongParameters]
  def certificate_holder_params
    raise NotImplementedError,
          "#{self.class.name}#certificate_holder_update_params is an abstract method."
  end

  # Form parameters that can be used to update the
  # certificate_holder instance
  #
  # @return [ActiveController::StrongParameters]
  def certificate_holder_update_params
    raise NotImplementedError,
          "#{self.class.name}#certificate_holder_update_params is an abstract method."
  end

  def passed_certificate
    # Storing the cert in the variable is required, as uploaded files (in RSpec
    # tests at least) will not be available for multiple calls:
    #
    # > passed_certificate.present? => true
    #
    # > passed_certificate.present?  => false
    @passed_cert ||= if certificate_holder_params[:certificate].present? ||
        certificate_holder_params[:current_cert].present?
      Certificate.find_or_initialize_by(
        certificate: Certificate.get_certificate_text(certificate_holder_params)
      )
    end
  end

  def create_or_update_certificate!
    if @cert.new_record?
      @cert.save!
    else
      @cert.update_attributes!(certificate: @passed_cert.certificate)
    end
    CertificateService.create(service: certificate_holder, certificate: @cert)
  end

  def set_certificate_holder
    @certificate_holder = certificate_holder_type.find(params[:id])
  end
end

app/controllers/settings/dex_connector_ldaps_controller.rb
# Settings::DexConnectorLdapsController is responsible to manage requests
# related to LDAP connectors.
class Settings::DexConnectorLdapsController < Settings::BaseCertificateController
  def index
    @ldap_connectors = DexConnectorLdap.all
  end

  def destroy
    @certificate_holder.destroy
    redirect_to settings_dex_connector_ldaps_path,
                notice: "LDAP Connector was successfully removed."
  end

  protected

  def certificate_holder_type
    DexConnectorLdap
  end

  def certificate_holder_params
    ldap_connector_params
  end

  def certificate_holder_update_params
    ldap_connector_params.except(:certificate, :current_cert)
  end

  private

  def ldap_connector_params
    params.require(:dex_connector_ldap).permit(:name, :host, :port,
                                               :start_tls, :certificate, :current_cert, :bind_anon,
                                               :bind_dn, :bind_pw, :username_prompt,
                                               :user_base_dn, :user_filter, :user_attr_username,
                                               :user_attr_id, :user_attr_email, :user_attr_name,
                                               :group_base_dn, :group_filter, :group_attr_user,
                                               :group_attr_group, :group_attr_name)
  end
end

app/controllers/settings/dex_connector_oidcs_controller.rb
# Settings::DexConnectorOidcsController is responsible to manage requests
# related to OIDC connectors.
class Settings::DexConnectorOidcsController < SettingsController
  # populate @data_holder with existing database record
  before_action :set_data_holder, except: [:index, :new, :create]

  def index
    @oidc_connectors = DexConnectorOidc.all
  end

  def new
    @is_data_valid = false
    @data_holder = data_holder_type.new
  end

  def edit
    @is_data_valid = false
  end

  def create
    @data_holder = data_holder_type.new(data_holder_params)

    if params[:validate]
      @is_data_valid = @data_holder.valid?
      if @is_data_valid
        flash.now[:notice] = "#{friendly_name} is valid"
      else
        flash.now[:alert]  = "#{friendly_name} is invalid"
      end
      render action: :new
    else
      @data_holder.save!
      redirect_to settings_dex_connector_oidcs_path,
                  notice: "#{friendly_name} was successfully created."
    end
  rescue ActiveRecord::RecordInvalid
    render action: :new, status: :unprocessable_entity
  end

  def destroy
    @data_holder.destroy!

    redirect_to settings_dex_connector_oidcs_path,
                notice: "OIDC Connector was successfully removed."
  end

  def update
    if params[:validate]
      # merge form values with DB record so form redisplays properly
      data_holder_update_params.each do |key, value|
        @data_holder[key] = value
      end
      @is_data_valid = @data_holder.valid?
      if @is_data_valid
        flash.now[:notice] = "#{friendly_name} is valid"
      else
        flash.now[:alert]  = "#{friendly_name} is invalid"
      end
      render action: :edit
    else
      @data_holder.update_attributes!(data_holder_update_params)
      redirect_to [:settings, @data_holder],
                  notice: "#{friendly_name} was successfully updated."
    end
  rescue ActiveRecord::RecordInvalid
    render action: :edit, status: :unprocessable_entity
  end

  protected

  def data_holder_type
    DexConnectorOidc
  end

  def data_holder_params
    oidc_connector_params
  end

  def data_holder_update_params
    oidc_connector_params
  end

  def friendly_name
    "OIDC Connector"
  end

  private

  def oidc_connector_params
    params.require(:dex_connector_oidc).permit(
      :name, :provider_url, :client_id, :client_secret, :callback_url, :basic_auth
    )
  end

  def set_data_holder
    @data_holder = data_holder_type.find(params[:id])
  end
end

app/controllers/settings/kubelet_compute_resources_reservations_controller.rb
# Settings::KubeletComputeResourcesReservations is responsibe to manage all the requests
# related to the kubelet compute resources reservations feature.
class Settings::KubeletComputeResourcesReservationsController < SettingsController
  def index
    @kube_reservations = KubeletComputeResourcesReservation.find_or_initialize_by(
      component: "kube"
    )
    @system_reservations = KubeletComputeResourcesReservation.find_or_initialize_by(
      component: "system"
    )
    @eviction_hard = Pillar.find_or_initialize_by(pillar: "kubelet:eviction-hard")
  end

  def create
    @kube_reservations = KubeletComputeResourcesReservation.find_or_initialize_by(
      component: "kube"
    )
    @system_reservations = KubeletComputeResourcesReservation.find_or_initialize_by(
      component: "system"
    )
    @eviction_hard = Pillar.find_or_initialize_by(pillar: "kubelet:eviction-hard")

    ActiveRecord::Base.transaction do
      @kube_reservations.update_attributes!(kube_reservation_params)
      @system_reservations.update_attributes!(system_reservation_params)
      @eviction_hard.update_or_remove!(eviction_hard_param)
    end

    redirect_to settings_kubelet_compute_resources_reservations_path,
      notice: "kubelet resource reservations successfully saved."
  rescue ActiveRecord::RecordInvalid => e
    Rails.logger.tagged(:kubelet_compute_resources_reservation) { Rails.logger.error e.message }
    render action: :index, status: :unprocessable_entity
  end

  private

  def kube_reservation_params
    ret = {}
    params.require(
      :kubelet_compute_resources_reservations
    ).permit(
      :kube_cpu,
      :kube_memory,
      :kube_ephemeral_storage
    ).each do |k, v|
      ret[k.gsub("kube_", "")] = v
    end
    ret
  end

  def system_reservation_params
    ret = {}
    params.require(
      :kubelet_compute_resources_reservations
    ).permit(
      :system_cpu,
      :system_memory,
      :system_ephemeral_storage
    ).each do |k, v|
      ret[k.gsub("system_", "")] = v
    end
    ret
  end

  def eviction_hard_param
    params["kubelet_compute_resources_reservations"]["eviction_hard"]
  end
end

app/helpers/settings_helper.rb
# SettingsHelper contains all the view helpers related/used in registries/mirrors templates.
module SettingsHelper
  def settings_path?
    request.fullpath.starts_with?(settings_path)
  end

  def settings_registries_path?
    request.fullpath.starts_with?(settings_registries_path)
  end

  def settings_registry_mirrors_path?
    request.fullpath.starts_with?(settings_registry_mirrors_path)
  end

  def settings_kubelet_compute_resources_reservations_path?
    request.fullpath.starts_with?(settings_kubelet_compute_resources_reservations_path)
  end

  def settings_auditing_index_path?
    request.fullpath.starts_with?(settings_auditing_index_path)
  end

  def settings_system_certificates_path?
    request.fullpath.starts_with?(settings_system_certificates_path)
  end

  def settings_dex_connector_ldaps_path?
    request.fullpath.starts_with?(settings_dex_connector_ldaps_path)
  end

  def settings_dex_connector_oidcs_path?
    request.fullpath.starts_with?(settings_dex_connector_oidcs_path)
  end

  def settings_external_cert_index_path?
    request.fullpath.starts_with?(settings_external_cert_index_path)
  end

  def registries_options_for_select
    registries = Registry.suse + Registry.displayable
    registries_for_options = registries.collect { |r| [r.name, r.id] }

    if params[:registry_id].present?
      options_for_select(registries_for_options, selected: params[:registry_id])
    else
      registries_for_options
    end
  end

  def display_registry_url(url)
    if url_secure?(url)
      content_tag(:i, nil, class: "fa fa-lock") + " " + url
    else
      url
    end
  end

  def url_secure?(url)
    url.starts_with?("https://") unless url.nil?
  end

  def suse_registry?(registry)
    registry.name == Registry::SUSE_REGISTRY_NAME
  end
end

app/views/settings/registry_mirrors/_form.html.slim
= form_for [:settings, @certificate_holder], html: { class: "mirror-form" } do |f|
  .form-group
    = f.label :registry_id, "Mirror of"
    .row
      .col-xs-4
        = f.select :registry_id, registries_options_for_select, { prompt: "Select a registry" }, class: "form-control registry-select", required: true, disabled: !@certificate_holder.new_record?
      - if @certificate_holder.new_record?
        .col-xs-8
          = link_to "Create new registry", new_settings_registry_path, class: "btn btn-primary add-entry-btn hide"
  .form-group class="#{error_class_for(@certificate_holder, :name)}"
    = f.label :name
    = f.text_field :name, class: "form-control", required: true
    = error_messages_for(@certificate_holder, :name)
  .form-group.form-group-url class="#{error_class_for(@certificate_holder, :url)}"
    = f.label :url, "URL"
    = f.text_field :url, class: "form-control url", required: true
    = error_messages_for(@certificate_holder, :url)
    span.help-block.invalid-format.hide This is not a valid URL. Please try something like https://registry.local
    span.help-block.invalid-insecure.hide Security warning: You are using an insecure mirror address for a secure remote registry
  .form-group.form-group-certificate class="#{'hide' unless url_secure?(@certificate_holder.url)} #{error_class_for(@cert, :certificate) if @cert.present?}"
    = f.label :certificate
    p Use this option to provide the self-signed certificate used by the mirror.
    = f.file_field :certificate, class: "form-control"
    - if @cert.present?
      = error_messages_for(@cert, :certificate)
      = f.text_area :current_cert, class: "form-control", value: @cert.certificate, rows: 7, readonly: "readonly"

  .form-actions.clearfix
    = f.submit "Save", class: "btn btn-primary action"
    = link_to "Cancel", settings_registry_mirrors_path, class: "btn btn-default action"

app/views/settings/registry_mirrors/edit.html.slim
h2 Edit

= render 'form'

app/views/settings/registry_mirrors/index.html.slim
= render 'settings/apply'

h2 Mirrors

= link_to "Add Mirror", new_settings_registry_mirror_path, class: "btn btn-primary add-entry-btn"

- if @grouped_mirrors.present?
  - @grouped_mirrors.each do |registry, mirrors|
    - if mirrors.present?
      section.panel.panel-default
        .panel-heading
          .panel-title
            strong.h4 = registry.name
        .panel-body
          table.table
            thead
              tr
                th width="30%" Name
                th URL
                th width="110"
            tbody
              - mirrors.each do |mirror|
                tr class="mirror_#{mirror.id}"
                  td
                    = link_to mirror.name, settings_registry_mirror_path(mirror), class: "details-link"
                  td
                    = display_registry_url(mirror.url)
                  td.actions
                    = link_to edit_settings_registry_mirror_path(mirror), class: "btn btn-default icon-only edit-btn" do
                      i.fa.fa-pencil
                    = link_to settings_registry_mirror_path(mirror), method: "delete", class: "btn btn-danger icon-only delete-btn", data: { confirm: "Are you sure?" } do
                      i.fa.fa-trash-o
- else
  p No mirrors found.

app/views/settings/registry_mirrors/new.html.slim
h2 New Mirror

= render 'form'

app/views/settings/registry_mirrors/show.html.slim
= render 'settings/apply'

header.settings-content-header.clearfix
  .title.pull-left
    h2 #{@certificate_holder.name} mirror details
  .actions.pull-right
    = link_to settings_registry_mirror_path(@certificate_holder), method: "delete", class: "btn btn-danger", data: { confirm: "Are you sure?" } do
      | Delete
    = link_to edit_settings_registry_mirror_path(@certificate_holder), class: "btn btn-primary" do
      | Edit

section.settings-details
  .field
    .details-label Registry
    .details-value
      - if suse_registry?(@certificate_holder.registry)
       = @certificate_holder.registry.name
      - else
        = link_to @certificate_holder.registry.name, settings_registry_path(@certificate_holder.registry), class: "registry-link"

  .field
    .details-label URL
    .details-value
      = display_registry_url(@certificate_holder.url)

  - if @certificate_holder.certificate.present?
    .field
      .details-label Certificate
      .details-value-certificate
        = @certificate_holder.certificate.certificate